### ISSUE TITLE
Italian Language

### ISSUE THREAD

**Issue by trisosamu** [clesssalvein/GlpiClient#1]
Can you implement italian language?

I attached to you translation of glpiClient.po
[glpiClient.txt](https://github.com/clesssalvein/GlpiClient/files/10465554/glpiClient.txt)

**Comment by clesssalvein** [comment]
Hmm. Sure. I'll post an app update when it's ready.

**Comment by trisosamu** [comment]
thank you

**Comment by trisosamu** [comment]
I make correctly italian translation with this 3 files ( glpiClient.po | glpiClient.mo | msgfmt.cmd )
so you don't have to do it

[msgfmt.cmd.txt](https://github.com/clesssalvein/GlpiClient/files/10466598/msgfmt.cmd.txt)
[glpiClient.po.txt](https://github.com/clesssalvein/GlpiClient/files/10466599/glpiClient.po.txt)
[glpiClient.mo.txt](https://github.com/clesssalvein/GlpiClient/files/10466600/glpiClient.mo.txt)

**Comment by clesssalvein** [comment]
Did you manage to add the interface translation to the app yourself?

**Comment by trisosamu** [comment]
Yes, I used "poedit" program to edit glpiClient.po file with italian translation

![image](https://user-images.githubusercontent.com/78987040/213706948-0ef764e0-3bcb-45d3-b5e0-0d2c768bc75a.png)

**Comment by clesssalvein** [comment]
Ok. I'll still add your translation to the next app update.

**Comment by clesssalvein** [comment]
Italian translation added (Thanks to [trisosamu](https://github.com/trisosamu)) in release [GlpiClient v0.304](https://github.com/clesssalvein/GlpiClient/releases/tag/v0.304)
